### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatCDAAC#25]
I've been working on a logo in illustrator and so far the time has not been productive 🙈

@jklenzing What program did you use for the original logo and do you still have that file in the original format?

**Comment by aburrell** [comment]
From what I remember:
- Yes, but on a different computer
- Also, the program is on that computer
- That computer requires that Jeff be in the office

I recommend sketching something and taking a picture, that can later be made into a nice logo.
